//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StevenVolckaert {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StevenVolckaert.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Exception in {1}: {2}.
        /// </summary>
        public static string DebugExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DebugExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}: {2}.
        /// </summary>
        public static string DebugMessageFormat {
            get {
                return ResourceManager.GetString("DebugMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an exception of type &apos;{0}&apos;..
        /// </summary>
        public static string EncounteredExceptionOfType {
            get {
                return ResourceManager.GetString("EncounteredExceptionOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid culture name..
        /// </summary>
        public static string IllegalCultureName {
            get {
                return ResourceManager.GetString("IllegalCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal enum value &apos;{0}&apos;..
        /// </summary>
        public static string IllegalEnumValue {
            get {
                return ResourceManager.GetString("IllegalEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal target type &apos;{0}&apos;..
        /// </summary>
        public static string IllegalTargetType {
            get {
                return ResourceManager.GetString("IllegalTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal type &apos;{0}&apos;. Expected type &apos;{1}&apos;..
        /// </summary>
        public static string IllegalType {
            get {
                return ResourceManager.GetString("IllegalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal value &apos;{0}&apos;..
        /// </summary>
        public static string IllegalValue {
            get {
                return ResourceManager.GetString("IllegalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; not found..
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute.
        /// </summary>
        public static string LessThanOneMinute {
            get {
                return ResourceManager.GetString("LessThanOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains no elements..
        /// </summary>
        public static string ValueContainsNoElements {
            get {
                return ResourceManager.GetString("ValueContainsNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains no supported elements..
        /// </summary>
        public static string ValueContainsNoSupportedElements {
            get {
                return ResourceManager.GetString("ValueContainsNoSupportedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value with ID &apos;{0}&apos; not found..
        /// </summary>
        public static string ValueNotFound {
            get {
                return ResourceManager.GetString("ValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not supported..
        /// </summary>
        public static string ValueNotSupported {
            get {
                return ResourceManager.GetString("ValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of parameter &apos;{0}&apos; is null..
        /// </summary>
        public static string ValueNull {
            get {
                return ResourceManager.GetString("ValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null, empty, or white space..
        /// </summary>
        public static string ValueNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null or empty..
        /// </summary>
        public static string ValueNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueNullOrEmpty", resourceCulture);
            }
        }
    }
}
